---
output: html_document
---

# Conclusions

### Regular Season Success

 - Minimize the 2nd, 3rd, and 4th opportunities and goals in rapid succession of opponents (Low flurryAdjustedxGoalsAgainst).  
 - Maintain an above average `xGoalsPercentage`
 - Shoot the puck. The more a team shoots, the higher chance of creating scoring oportunities. Apart from the 2017 season most playoff teams had the highest shots per game. The quality of shots can improve the scoring chance of scoring though the data showed that being a leader in any of the low, medium, or high danger shots can merit playoff contention. `CorsiPercentage` compares the shot differential between the two teams. Having a high `CorsiPercentage` at even strength is a strong indicator of a sucessful team.
 - Mitigate shots on your own goalie. The data showed that playoff teams reduced the number of shots their own goalie faced. Some seasons, shot blocking was a factor for playoff teams and other seasons focused on other methods of reducing opponent shots not quantified in this analysis.
 - Strong goaltending. A combination of save percentage and goals against can be used to analyze the effectiveness of a goalie. It is important to have a good balance between the two stats as if many shots are taken, the save percentage will be good, but many goals are bound to go in. There is a strong correlation between good goaltending and playoff qualification.
 - Winning Faceoffs. Teams with a faceoff percentage of 50% or better in 4 on 5 situations had much lower goals against on average. Puck possession is vital on draws in key situations, such as a penalty kill.
 
 
### Playoff Success

 - Shot volume appears to be less valuable in the playoffs compared to the quality of the shot. 
 - `CorsiPercentage` could be used as a good proxy for playoff performance as most successful teams are close or exceed 50% of all shot attempts.
 - Interestingly, shot block leaders each season failed to progress past the second round of the playoffs. 
 - Desciplined teams are more likely to progress to at least the third round of the playoffs.
 - Winning Faceoffs appear to be valuable for in odd man situations (4on5 and 5on4). Teams that are above or close to the historic average tend to progress deep into the playoffs.
 - Physicality is a big part of ice hockey. The data shows that it is valuable to have an average amount of hits, too little can reduce the fear or intimidation factor and too many can turn into penalties and lead to players being out of position to finish a hit.
 - In the playoffs a hot goaltender can go a long way. A target save percentage and goals against average should appears to be 0.9 percent and 3 goals, respectively. 